import type { MarketNews } from '@/types/news';

export const mockNews: MarketNews[] = [
  {
    id: 'fallback-1',
    title: '미국 금리 전망 변화에 원/달러 환율 변동성 확대',
    summary: '연준 발언과 국채금리 흐름이 국내 증시 수급과 성장주 밸류에이션에 영향을 줄 수 있습니다.',
    source: '연합인포맥스',
    originalUrl: 'https://example.com/news/1',
    publishedAt: new Date().toISOString(),
    importanceScore: 94,
    reliabilityScore: 84,
    opinionScore: 12,
    freshnessScore: 100,
    finalScore: 90,
    contentType: 'official_news',
    marketRegion: 'us',
    marketRegionLabel: '미국경제',
    qualityLabel: '공식뉴스',
    sentiment: 'neutral',
    tags: ['금리', '환율'],
    relatedStocks: [],
    reason: '거시경제 핵심 변수인 금리와 환율이 동시에 포함되어 높은 중요도로 분류했습니다.'
  },
  {
    id: 'fallback-2',
    title: 'AI 서버 투자 확대로 HBM·반도체 장비주 관심 지속',
    summary: '데이터센터 투자와 고대역폭메모리 수요가 반도체 후공정 장비 기업에 영향을 줄 수 있습니다.',
    source: '전자신문',
    originalUrl: 'https://example.com/news/2',
    publishedAt: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
    importanceScore: 90,
    reliabilityScore: 82,
    opinionScore: 18,
    freshnessScore: 90,
    finalScore: 82,
    contentType: 'official_news',
    marketRegion: 'korea',
    marketRegionLabel: '한국경제',
    qualityLabel: '공식뉴스',
    sentiment: 'positive',
    tags: ['AI', 'HBM', '반도체'],
    relatedStocks: ['테크윙', 'SK하이닉스'],
    reason: 'AI, HBM, 반도체가 동시에 연결되어 관심 테마 우선순위를 높였습니다.'
  },
  {
    id: 'fallback-3',
    title: 'LNG선 발주 기대감에 조선 업종 주목',
    summary: '글로벌 선박 발주와 에너지 운송 수요 회복 기대가 조선주 투자심리에 영향을 줄 수 있습니다.',
    source: '서울경제',
    originalUrl: 'https://example.com/news/3',
    publishedAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    importanceScore: 78,
    reliabilityScore: 84,
    opinionScore: 18,
    freshnessScore: 90,
    finalScore: 75,
    contentType: 'official_news',
    marketRegion: 'korea',
    marketRegionLabel: '한국경제',
    qualityLabel: '공식뉴스',
    sentiment: 'positive',
    tags: ['조선'],
    relatedStocks: ['삼성중공업'],
    reason: '관심 업종과 관련 종목이 포함되어 중상위 중요도로 분류했습니다.'
  }
];
